services:
  backend:
    build:
      context: backend
    env_file:
      - backend/.env
    ports:
      - "3000:8080"
      - "5555:5555"
    restart: unless-stopped
    depends_on:
      - db
      - mosquitto

  db:
    image: postgres:16
    env_file:
      - backend/.env
    volumes:
      - iotdbvolume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  iotdbvolume: